### ISSUE TITLE
Share View Custom 관련 이슈

### ISSUE THREAD

**Issue by brido4125** [Send-wish/Front-End#21]
## 현재 적용된 커스텀 뷰 이미지
![Simulator Screen Shot - iPhone 14 - 2023-01-10 at 22 13 10](https://user-images.githubusercontent.com/64846408/211703797-5c5a21dc-0efa-479c-97da-0ba4ad668a08.png)
## 추후 적용시키고 싶은 이미지
<img width="598" alt="스크린샷 2023-01-11 오전 10 34 41" src="https://user-images.githubusercontent.com/64846408/211703852-605a44ef-7e7c-4550-a3de-5d81c1759afb.png">

## 문제점
- 위 두 사진의 차이처럼 기본으로 깔리는 **흰색 배경의 사이즈 자체를 줄이고 싶습니다.(추가적으로 가능하다면 opacity 및 background color 도 수정하고 싶습니다)**
- 이를 RN 문법으로 해당 커스텀 뷰 자체를 수정하려고 하니 아래와 같이 CSS만 변경되는 문제가 발생합니다.
- 제 생각에는 `ios/share/ReactShareViewController.swift` 또는 `Info.plist`파일을 변경하면 하얀색 모달이 변경이 될 것 같은데 해당 부분에서 어려움을 겪고 있습니다.
- @prodia4 멘토님께서 보시기에 스위프트로 개선이 가능한 부분이면 도움을 좀 부탁드리고 싶습니다! 

![Simulator Screen Shot - iPhone 14 - 2023-01-10 at 22 13 01](https://user-images.githubusercontent.com/64846408/211703989-bde665a4-f969-43c5-8ec9-3b7d5ccfdd47.png)

**Comment by prodia4** [comment]
`ReactShareViewController`가 배경 색을 설정할 때 사용하는 `Info.plist`에서 배경색을 투명하게 바꾸신 후, 나머지는 JS에서 뷰를 하단에만 그리도록 변경하시면 될 것 같습니다.

**Comment by prodia4** [comment]
위시버킷과 비슷하게 가려면 아예 투명하게 하기보다는 alpha값이 낮은 어두운 배경으로 하는 것도 좋겠네요.

배경색은 굳이 `Info.plist`를 읽도록 하지 말고 `ReactShareViewController`에서 직접 세팅하셔도 됩니다.
